### ISSUE TITLE
Bug with Angular 6 AOT

### ISSUE THREAD

**Issue by djdany01** [djdany01/MyWatchList#2]
Using NgProgressModule and build with AOT throws an error.
Known bug with Angular 6
[Related Issue Angular](https://github.com/angular/angular/issues/23609)

Build without AOT for now.

**Comment by djdany01** [comment]
Translations doesn't function without AOT

**Comment by Sevensnake** [comment]
having the same problem building with Aot but tells me 
Cannot determine the module for class EqualPipe in C:/git/component.ts! Add EqualPipe to the NgModule to fix it.

doesn't make since, since I have these pages a part of a module in delclarations.

**Comment by djdany01** [comment]
The bug with AOT is fixed in the last update.
And I don't know what is the EqualPipe, is never used in my code, open new Issue if you want.
This is closed :D
